CREATE DATABASE IF NOT EXISTS asterisk DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER IF NOT EXISTS 'cron'@'%' IDENTIFIED BY '1234';
GRANT SELECT,CREATE,ALTER,INSERT,UPDATE,DELETE,LOCK TABLES on asterisk.* TO cron@'%';
GRANT RELOAD ON *.* TO cron@'%';
CREATE USER IF NOT EXISTS 'custom'@'%' IDENTIFIED BY 'custom1234';
GRANT SELECT,CREATE,ALTER,INSERT,UPDATE,DELETE,LOCK TABLES on asterisk.* TO custom@'%';
GRANT RELOAD ON *.* TO custom@'%';
FLUSH PRIVILEGES;
SET GLOBAL connect_timeout=60;
